name: Custom Package CI/CD

on:
  push:
    branches: [main]  # Trigger on pushes to the main branch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3 # Check out the code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10 # Or your desired version

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install .  # Install your custom package

      - name: Run tests
        run: pytest  # Or your test command

      - name: Train model
        run: python path/to/your/training_script.py

      - name: Create model artifact (Optional)
        uses: actions/upload-artifact@v3
        with:
          name: trained_model
          path: path/to/your/model.pkl  # Or the saved model location
      
      - name: Deploy to Platform
        run: |
          python deployment_script.py \
            --model path/to/your/model.pkl
