apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
    environment: prod
spec:
  containers:
  - name: myapp
    image: manifoldailearning/custom-nginx
    ports:
      - containerPort: 80


